name: Create Release

on:
  push:
    branches: [main]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get last tag
        id: last_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
      - name: Get commits since last tag
        id: commits
        run: |
          echo "Commits since last release:"
          git log ${{ steps.last_tag.outputs.tag }}..HEAD --pretty=format:'- %s%n'
        shell: bash
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is a new release.
          draft: false
          prerelease: false
      - name: Add commits to release body
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const { data: { body: currentBody } } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context
