name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get last release tag
        id: last_release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });
            const lastRelease = releases[0];
            console.log(`Last release tag: ${lastRelease.tag_name}`);
            return { tag: lastRelease.tag_name };
      - name: Get commits since last release
        id: commits_since_last_release
        run: |
          git fetch --tags
          echo "::set-output name=commits::$(git log --pretty=format:'- %s%n' ${GITHUB_REF}..${{ steps.last_release.outputs.tag }})"
        shell: bash
      - name: Create Release
        uses: actions/create-release@v1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            This is a new release.
            Commits since last release:
            ${{ steps.commits_since_last_release.outputs.commits }}
          draft: false
          prerelease: false
