name: Create Release

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract Pull Request Number and Commit ID
      id: extract_info
      run: |
        PR_NUMBER=$(echo ${{ github.event.pull_request.number }})
        COMMIT_ID=$(echo ${{ github.event.pull_request.head.sha }})
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.PR_NUMBER }}_${{ env.COMMIT_ID }}
        release_name: Release ${{ env.PR_NUMBER }}_${{ env.COMMIT_ID }}
        body: |
          New release ${{ env.PR_NUMBER }}_${{ env.COMMIT_ID }} of your Python project.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
